steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sospitas', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sospitas']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'sospitas'
      - '--image=europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sospitas'
      - '--region=europe-west2'
      - '--platform=managed'

images:
  - 'europe-west2-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/sospitas'
